// 🚀 Josidk Template — embed-sources.mjs
// Pre-build script: reads all project source files and generates a TypeScript
// map so the Settings component can build a full-project ZIP in the browser.
//
// Usage:  node scripts/embed-sources.mjs
// Called automatically via "prestart" and "prebuild" npm scripts.

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, dirname, relative, extname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, '..');
const OUTPUT_PATH = join(PROJECT_ROOT, 'src', 'app', 'pages', 'settings', 'project-sources.ts');

// ─── Configuration ───

/** Directories to scan (relative to PROJECT_ROOT) */
const SCAN_DIRS = ['src', 'public'];

/** Root-level files to include */
const ROOT_FILES = [
  'package.json',
  'package-lock.json',
  'angular.json',
  'tsconfig.json',
  'tsconfig.app.json',
  'tsconfig.spec.json',
  '.editorconfig',
  '.gitignore',
  'README.md',
  'DOCUMENTACION.md',
];

/** Patterns to exclude (checked against relative path) */
const EXCLUDE_PATTERNS = [
  /node_modules/,
  /\.git[\\/]/,
  /\.angular[\\/]/,
  /dist[\\/]/,
  /\.vscode[\\/]/,
  /\.continue[\\/]/,
  /\.spec\.ts$/,
  /project-sources\.ts$/,      // Don't embed ourselves
  /scripts[\\/]embed-sources/,  // Don't embed this script
];

/** Binary file extensions (will be Base64-encoded) */
const BINARY_EXTENSIONS = new Set([
  '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico',
  '.woff', '.woff2', '.ttf', '.eot',
  '.pdf', '.zip', '.gz',
]);

// ─── Helpers ───

function isBinary(filePath) {
  return BINARY_EXTENSIONS.has(extname(filePath).toLowerCase());
}

function isExcluded(relativePath) {
  return EXCLUDE_PATTERNS.some(pattern => pattern.test(relativePath));
}

function walkDir(dir, fileList = []) {
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    const relPath = relative(PROJECT_ROOT, fullPath).replace(/\\/g, '/');

    if (isExcluded(relPath)) continue;

    if (entry.isDirectory()) {
      walkDir(fullPath, fileList);
    } else if (entry.isFile()) {
      fileList.push({ fullPath, relPath });
    }
  }
  return fileList;
}

function escapeForTemplate(str) {
  // Escape backticks and ${} in template literals
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

// ─── Main ───

console.log('📦 Embebiendo archivos fuente del proyecto...\n');

const files = [];

// 1. Scan directories
for (const dir of SCAN_DIRS) {
  const dirPath = join(PROJECT_ROOT, dir);
  walkDir(dirPath, files);
}

// 2. Include root files
for (const fileName of ROOT_FILES) {
  const fullPath = join(PROJECT_ROOT, fileName);
  try {
    statSync(fullPath);
    const relPath = fileName.replace(/\\/g, '/');
    if (!isExcluded(relPath)) {
      files.push({ fullPath, relPath });
    }
  } catch {
    // File doesn't exist, skip
  }
}

// 3. Generate TypeScript output
let textCount = 0;
let binaryCount = 0;

const entries = [];

for (const { fullPath, relPath } of files) {
  const binary = isBinary(fullPath);

  if (binary) {
    const b64 = readFileSync(fullPath).toString('base64');
    entries.push(`  ['${relPath}', { content: '${b64}', binary: true }]`);
    binaryCount++;
  } else {
    const raw = readFileSync(fullPath, 'utf-8');
    const escaped = escapeForTemplate(raw);
    entries.push(`  ['${relPath}', { content: \`${escaped}\`, binary: false }]`);
    textCount++;
  }
}

const output = `// ⚡ Auto-generated by scripts/embed-sources.mjs
// DO NOT EDIT MANUALLY — re-run: node scripts/embed-sources.mjs
// Generated: ${new Date().toISOString()}
// Files: ${files.length} (${textCount} text, ${binaryCount} binary)

export interface ProjectFile {
  content: string;
  binary: boolean;
}

export const PROJECT_FILES: Map<string, ProjectFile> = new Map([
${entries.join(',\n')}
]);
`;

writeFileSync(OUTPUT_PATH, output, 'utf-8');

console.log(`  ✅ ${files.length} archivos embebidos (${textCount} texto, ${binaryCount} binarios)`);
console.log(`  📄 Generado: src/app/pages/settings/project-sources.ts`);
console.log(`  📏 Tamaño: ${(Buffer.byteLength(output) / 1024).toFixed(1)} KB\n`);
